import { createClient } from '@supabase/supabase-js';
import * as dotenv from 'dotenv';
import * as path from 'path';

// Load environment variables
dotenv.config({ path: path.join(__dirname, '..', '.env.local') });

// Use service role key to bypass RLS for batch updates
const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

async function cleanupSearchTerms() {
  console.log('Fetching all exercises...\n');

  const { data: exercises, error } = await supabase
    .from('exercises')
    .select('id, name, category, subcategory, tags, equipment, body_parts, search_terms');

  if (error) {
    console.error('Error fetching exercises:', error);
    return;
  }

  console.log(`Found ${exercises.length} exercises\n`);

  let updatedCount = 0;
  let skippedCount = 0;

  for (const exercise of exercises) {
    if (!exercise.search_terms) {
      skippedCount++;
      continue;
    }

    // Parse current search terms (split by spaces and commas, remove punctuation)
    const currentTerms = exercise.search_terms
      .toLowerCase()
      .split(/[\s,]+/)
      .map(term => term.replace(/[.,;:!?()[\]{}'"]/g, ''))
      .filter(Boolean);

    // Get all searchable field terms (all lowercase)
    // Arrays: keep whole terms AND their word parts (search uses .includes() which handles both)
    const tags = (exercise.tags || []).map((t: string) => t.toLowerCase());
    const equipment = (exercise.equipment || []).map((e: string) => e.toLowerCase());
    const bodyParts = (exercise.body_parts || []).map((bp: string) => bp.toLowerCase());

    // Also split to individual words for partial matching
    const tagWords = tags.flatMap(t => t.split(/[-\s]+/)).filter(Boolean);
    const equipmentWords = equipment.flatMap(e => e.split(/[-\s]+/)).filter(Boolean);
    const bodyPartWords = bodyParts.flatMap(bp => bp.split(/[-\s]+/)).filter(Boolean);

    const nameParts = exercise.name.toLowerCase().split(/[-\s]+/).filter(Boolean);
    const categoryParts = exercise.category.toLowerCase().split(/[-\s]+/).filter(Boolean);
    const subcategoryParts = exercise.subcategory
      ? exercise.subcategory.toLowerCase().split(/[-\s]+/).filter(Boolean)
      : [];

    // Terms that are searchable (whole terms + word parts)
    const autoGeneratedTerms = new Set([
      ...nameParts,
      ...categoryParts,
      ...subcategoryParts,
      ...tags,
      ...equipment,
      ...bodyParts,
      ...tagWords,
      ...equipmentWords,
      ...bodyPartWords
    ]);

    // Keep only unique terms (not in auto-generated)
    const uniqueTerms = currentTerms.filter(term => !autoGeneratedTerms.has(term));

    const newSearchTerms = uniqueTerms.join(' ').trim();

    // Only update if there's a change
    if (newSearchTerms !== exercise.search_terms) {
      const { error: updateError } = await supabase
        .from('exercises')
        .update({ search_terms: newSearchTerms || null })
        .eq('id', exercise.id);

      if (updateError) {
        console.error(`Error updating ${exercise.name}:`, updateError);
      } else {
        console.log(`✓ ${exercise.name}`);
        console.log(`  Before: "${exercise.search_terms}"`);
        console.log(`  After:  "${newSearchTerms || '(empty - auto-generated)'}"\n`);
        updatedCount++;
      }
    } else {
      skippedCount++;
    }
  }

  console.log('\n=== Summary ===');
  console.log(`Updated: ${updatedCount}`);
  console.log(`Skipped (no changes): ${skippedCount}`);
  console.log(`Total: ${exercises.length}`);
}

cleanupSearchTerms().catch(console.error);
