SELECT
  (SELECT COUNT(*) FROM wod_section_results r LEFT JOIN weekly_sessions ws ON ws.workout_id = r.wod_id WHERE ws.id IS NULL) AS stray_section_results,
  (SELECT COUNT(*) FROM wod_section_results r JOIN weekly_sessions ws ON ws.workout_id = r.wod_id LEFT JOIN bookings b ON b.session_id = ws.id AND (b.member_id = r.user_id OR b.member_id IN (SELECT m.id FROM members m WHERE m.email = (SELECT email FROM auth.users WHERE id = r.user_id) OR m.primary_member_id IN (SELECT m2.id FROM members m2 WHERE m2.email = (SELECT email FROM auth.users WHERE id = r.user_id)))) WHERE b.id IS NULL) AS unbooked_section_results,
  (SELECT COUNT(*) FROM workout_logs wl LEFT JOIN wods w ON w.id = wl.wod_id WHERE w.id IS NULL) AS orphan_workout_logs,
  (SELECT COUNT(*) FROM bookings b LEFT JOIN weekly_sessions ws ON ws.id = b.session_id WHERE ws.id IS NULL) AS orphan_bookings,
  (SELECT COUNT(*) FROM reactions r LEFT JOIN wod_section_results wsr ON wsr.id = r.target_id WHERE r.target_type = 'wod_section_result' AND wsr.id IS NULL) AS orphan_reactions_section,
  (SELECT COUNT(*) FROM reactions r LEFT JOIN benchmark_results br ON br.id = r.target_id WHERE r.target_type = 'benchmark_result' AND br.id IS NULL) AS orphan_reactions_benchmark,
  (SELECT COUNT(*) FROM reactions r LEFT JOIN lift_records lr ON lr.id = r.target_id WHERE r.target_type = 'lift_record' AND lr.id IS NULL) AS orphan_reactions_lift,
  (SELECT COUNT(*) FROM wods w LEFT JOIN weekly_sessions ws ON ws.workout_id = w.id WHERE ws.id IS NULL AND w.google_event_id IS NOT NULL) AS gcal_orphan_wods,
  (SELECT COUNT(*) FROM wod_section_results r LEFT JOIN wods w ON w.id = r.wod_id WHERE w.id IS NULL) AS results_deleted_wods,
  (SELECT COUNT(*) FROM bookings b LEFT JOIN members m ON m.id = b.member_id WHERE m.id IS NULL) AS orphan_bookings_no_member,
  (SELECT COUNT(*) FROM (SELECT COALESCE(user_id::text, 'wb:' || whiteboard_name, 'mb:' || member_id::text), wod_id, section_id FROM wod_section_results GROUP BY COALESCE(user_id::text, 'wb:' || whiteboard_name, 'mb:' || member_id::text), wod_id, section_id HAVING COUNT(*) > 1) d) AS duplicate_section_results,
  (SELECT COUNT(*) FROM (SELECT user_id, benchmark_name, result_date FROM benchmark_results GROUP BY user_id, benchmark_name, result_date HAVING COUNT(*) > 1) d) AS duplicate_benchmarks,
  (SELECT COUNT(*) FROM (SELECT user_id, lift_name, lift_date, rep_max_type, rep_scheme FROM lift_records GROUP BY user_id, lift_name, lift_date, rep_max_type, rep_scheme HAVING COUNT(*) > 1) d) AS duplicate_lifts,
  (SELECT COUNT(*) FROM wods WHERE workout_publish_status = 'published' AND (workout_name IS NULL OR workout_name = '')) AS published_wods_no_name,
  (SELECT COUNT(*) FROM athlete_achievements aa LEFT JOIN achievement_definitions ad ON ad.id = aa.achievement_id LEFT JOIN auth.users u ON u.id = aa.user_id WHERE ad.id IS NULL OR u.id IS NULL) AS orphan_athlete_achievements,
  (SELECT COUNT(*) FROM benchmark_results br LEFT JOIN benchmark_workouts bw ON bw.id = br.benchmark_id LEFT JOIN forge_benchmarks fb ON fb.id = br.forge_benchmark_id WHERE (br.benchmark_id IS NOT NULL AND bw.id IS NULL) OR (br.forge_benchmark_id IS NOT NULL AND fb.id IS NULL)) AS orphan_benchmark_results,
  (SELECT COUNT(*) FROM members m WHERE m.account_type = 'family_member' AND m.primary_member_id IS NOT NULL AND m.primary_member_id NOT IN (SELECT id FROM members)) AS orphan_family_members,
  (SELECT COUNT(*) FROM wod_section_results r LEFT JOIN members m ON m.id = r.member_id WHERE r.member_id IS NOT NULL AND m.id IS NULL) AS orphan_section_results_member_id,
  (SELECT COUNT(*) FROM programming_plan_items ppi LEFT JOIN movement_patterns mp ON mp.id = ppi.pattern_id WHERE mp.id IS NULL) AS orphan_programming_plan_items,
  (SELECT COUNT(*) FROM movement_pattern_exercises mpe LEFT JOIN movement_patterns mp ON mp.id = mpe.pattern_id LEFT JOIN exercises e ON e.id = mpe.exercise_id WHERE mp.id IS NULL OR e.id IS NULL) AS orphan_pattern_exercises,
  (SELECT COUNT(*) FROM user_exercise_favorites uef LEFT JOIN exercises e ON e.id = uef.exercise_id LEFT JOIN auth.users u ON u.id = uef.user_id WHERE e.id IS NULL OR u.id IS NULL) AS orphan_favorites,
  (SELECT COUNT(*) FROM coach_tracked_exercises cte LEFT JOIN exercises e ON e.id = cte.exercise_id LEFT JOIN auth.users u ON u.id = cte.user_id WHERE e.id IS NULL OR u.id IS NULL) AS orphan_coach_tracked,
  (SELECT COUNT(*) FROM weekly_sessions ws LEFT JOIN bookings b ON b.session_id = ws.id WHERE ws.workout_id IS NULL AND b.id IS NULL) AS empty_sessions_no_bookings,
  (SELECT COUNT(*) FROM wods w LEFT JOIN weekly_sessions ws ON ws.workout_id = w.id WHERE ws.id IS NULL) AS orphan_wods;
